[cerebrium.deployment]
name = "iris-classifier"
python_version = "3.10"
include = ["*"]
exclude = [".*"]
shell_commands = ["pip install --upgrade pip setuptools wheel"]

[cerebrium.runtime.custom]
port = 5000
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 1
memory = 2.0
compute = "CPU"
gpu_count = 0

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 10

[cerebrium.dependencies.pip]
scikit-learn = "1.3.0"
joblib = "1.3.2"
numpy = "1.24.3"
pandas = "2.0.3"
fastapi = "latest"
pydantic = "latest"
uvicorn = "latest"
